#!/usr/bin/env bash
# Bash script display information about subdomains
if [ $# -eq 1 ]
	then
		subd='www lb-01 web-01 web-02'
else
	subd="$2"
fi
for sub in $subd
	do
		echo -n "The subdomain $sub"
		dig "$sub.$1" | awk 'NR == 14 {printf " is a %s record and points to %s\n", $4, $5}'
done
